### ISSUE TITLE
Please add some references to papers

### ISSUE THREAD

**Issue by EricCreusen** [samuelmurray/tracking-by-detection#1]
I came here from the MOT challenge website interested in your tracker. Could you please add some references to publications in the readme so I can learn more about how it works?

**Comment by samuelmurray** [comment]
I'm sorry the readme is not really up to date. I will make it more complete once the corresponding paper is complete. For now I can direct you to another project - https://github.com/abewley/sort - from which I took inspiration. I can bump this thread once I add my own work.

**Comment by EricCreusen** [comment]
Much appreciated, I look forward to reading your paper.

**Comment by ChampionLi** [comment]
I also came here from the MOT challenge website interested in your tracker and noticed that your paper could be got in August. I'm wondering if we can refer to your paper now. Thank you.

**Comment by samuelmurray** [comment]
Hello, I'm very sorry it's been delayed this much. I submitted the report to arxiv just now, so it should be up in a few days! Will post the link.

**Comment by EricCreusen** [comment]
Much appreciated. I understand writing papers can take a long time (I've been there myself). 

I still look forward to reading your paper.

**Comment by samuelmurray** [comment]
The report (or more accurately the _thesis_) is now on arxiv! 
Real-Time Multiple Object Tracking - A Study on the Importance of Speed
https://arxiv.org/abs/1709.03572

I will update the readme.md and the MOTChallenge submission later today.

**Comment by ChampionLi** [comment]
Thank you very much for your paper and work!
