### ISSUE TITLE
Is there any threshold I could adjust with my own data?

### ISSUE THREAD

**Issue by iamweiweishi** [samuelmurray/tracking-by-detection#13]
Hi there,
Thank you for your great contribution. I run the detectAndtrack code, the result is not bad. But there still exists obviously missing tracking ID between Neighboring frames. So Is there any threshold I could adjust with my own data.
Many thanks.

**Comment by samuelmurray** [comment]
Yes, the `affinityThreshold` in PAOT determines how matching two detections should be for them to be connected by the tracker.

**Comment by iamweiweishi** [comment]
GREAT. Thank you again.
