### ISSUE TITLE
detectAndTrack usage

### ISSUE THREAD

**Issue by Anabad** [samuelmurray/tracking-by-detection#8]
I'm attempting to use the detectAndTrack demo, but I'm having issues with the configuration files.
For the **models** part, I've put the caffe ssd model under tracking-by-detection/models, and my model_config.txt file looks like this.

```
<model-type>
deploy.prototxt
VGG_VOC0712_SSD_300x300_iter_120000.caffemodel
<r_mean,g_mean,b_mean>
```

For the seqmap.txt file, I don't know what to do since I don't have any detections to point to, I thought the point of detectAndTrack was to have SSD do the detections.

What should the configuration look like?

if it helps my images are stored as data/myimages/images/xxxxx.jpg

Any help would be very much appreciated.

**Comment by samuelmurray** [comment]
By looking at it again, I agree that it's a bit confusion. But it seems that I used seqmap is used either to point to the images or the detection files. Actually, I rarely used the detectAndTrack demo myself. But I believe with your structure, the seqmap should simply be 
```
myimages
```
